### ISSUE TITLE
Readme Edit - change options key to transport_options

### ISSUE THREAD

**Issue by davidbwire** [goalio/GoalioMailService#13]
Could you change this
$settings = array(
    'transport_class' => 'Zend\Mail\Transport\Smtp',

    'options_class' => 'Zend\Mail\Transport\SmtpOptions',

    'options' => array(
        'host' => 'smtp.gmail.com',
        'connection_class' => 'login',
        'connection_config' => array(
            'ssl' => 'tls',
            'username' => 'YOUR-USERNAME-HERE@gmail.com',
            'password' => 'YOUR-PASSWORD-HERE'
        ),
        'port' => 587
    )
);
to 
$settings = array(
    'transport_class' => 'Zend\Mail\Transport\Smtp',

    'options_class' => 'Zend\Mail\Transport\SmtpOptions',

    'transport_options' => array(
        'host' => 'smtp.gmail.com',
        'connection_class' => 'login',
        'connection_config' => array(
            'ssl' => 'tls',
            'username' => 'YOUR-USERNAME-HERE@gmail.com',
            'password' => 'YOUR-PASSWORD-HERE'
        ),
        'port' => 587
    )
);
The first one is misleading and leads to a Zend\ServiceManager\Exception\ServiceNotCreatedException when requesting for password reset.  With the edit, everything goes fine.

**Comment by arielkruger1989** [comment]
I had to add this line to make it work. Before adding this line it was taking about two minutes to send my emails. 

``` javascript
'type' => 'smtp'
```

I hope it helps someone.
