### ISSUE TITLE
Mail attachment support

### ISSUE THREAD

**Issue by jeffchulg** [goalio/GoalioMailService#2]
Hi, does your MailService support mail attachments ?

**Comment by Rahat032** [comment]
I am using this 
$message = $mailService->createHtmlMessage($from, $to, $subject, $viewTemplate, $values);
                        $message->createAttachment('public/data/myfile.pdf',
                        'doc/pdf',
                        Zend\Mime\Mime::DISPOSITION_INLINE,
                        Zend\Mime\Mime::ENCODING_BASE64);
                        $mailService->send($message);
but it giving me this error 
"Call to undefined method Zend\Mail\Message::createAttachment() in"
