### ISSUE TITLE
 Fatal error: Uncaught exception 'Zend\ModuleManager\Exception\RuntimeException' with message 'Module (GoalioMailService) could not be initialized.

### ISSUE THREAD

**Issue by carduini** [goalio/GoalioMailService#21]
I try to install GoalioMailservice without success

here the error when i open my website
 Fatal error: Uncaught exception 'Zend\ModuleManager\Exception\RuntimeException' with message 'Module (GoalioMailService) could not be initialized.' in /var/www/myproject/vendor/zendframework/zendframework/library/Zend/ModuleManager/ModuleManager.php on line 195

Zend\ModuleManager\Exception\RuntimeException: Module (GoalioMailService) could not be initialized. in /var/www/myproject/vendor/zendframework/zendframework/library/Zend/ModuleManager/ModuleManager.php on line 195

I follow the readme file and i follow the step but without success.
I have zfc-user 1.2.3 on my sistem.

**Comment by pdobrigkeit** [comment]
That is strange. Could you check in `./vendor/composer/autoload_namespaces.php` if the line `'GoalioMailService' => array($vendorDir . '/goalio/goalio-mailservice/src'),` is present? Also the directory `./vendor/goalio/goalio-mailservice` is correctly installed?

**Comment by carduini** [comment]
autoload_namespaces.php is correct and also the directory is correctly installed.

**Comment by carduini** [comment]
I try to remove it from application.config.php and reinsert it... now it's working!
thanks.
